#define MENU_SEPARADOR "###########################################################\n"
#define MENU_DATA_TYPE "#\t\t\t\t\t\tTipo de Dados\t\t\t\t\t  #\n"
#define MENU_DATA_EXIT "#\t0.Sair do programa\t\t\t\t\t\t\t\t\t  #\n"
#define MENU_DATA_TYPE_OPTION "\nEscolha o tipo de dados: "
#define MENU_DATA_TYPE_STRING_LENGTH "\nIntroduza o comprimento da string(Ex:5;100): "
#define MENU_DATA_TYPE_DECIMAL_LENGTH "\nIntroduza o comprimento da parte decimal(Ex:2;5): "
#define MENU_DATA_TYPE_STRING_TYPE1 "#\t1.Letras Maiúsculas + espaço\t\t\t\t\t\t  #\n"
#define MENU_DATA_TYPE_STRING_TYPE2 "#\t2.Letras minúsculas + espaço\t\t\t\t\t\t  #\n"
#define MENU_DATA_TYPE_STRING_TYPE3 "#\t3.Letras Maiúsculas + espaço + caracteres especiais   #\n"
#define MENU_DATA_TYPE_STRING_TYPE4 "#\t4.Letras minúsculas + espaço + caracteres especiais   #\n"
#define MENU_DATA_TYPE_NUM_TYPE1 "#\t5.Números inteiros\t\t\t\t\t\t\t\t\t  #\n"
#define MENU_DATA_TYPE_NUM_TYPE2 "#\t6.Números decimais\t\t\t\t\t\t\t\t\t  #\n"
#define MENU_DATA_TYPE_STRING_TYPE5 "#\t7.Letras Maiúsculas + minúsculas + números + espaço   #\n"
#define MENU_DATA_TYPE_STRING_TYPE6 "#\t8.Todos os caracteres\t\t\t\t\t\t\t\t  #\n"
#define MENU_DATA_ENTRY "\n\nIntroduza os dados que deseja: "
#define MENU_DATA_RESULT "Dados inseridos: %s\n\n"
#define MENU_EXIT_PROGRAM "\n\nA sair do programa..."
