#define MENU_SEPARADOR "###########################################################\n"
#define MENU_DATA_TYPE "#                      Tipo de Dados                      #\n"
#define MENU_DATA_EXIT "#   0.Sair do programa\t\t\t\t\t\t\t\t\t  #\n"
#define MENU_DATA_TYPE_OPTION "\nEscolha o tipo de dados: "
#define MENU_DATA_TYPE_STRING_LENGTH "\nIntroduza o comprimento da string(Ex:5;100): "
#define MENU_DATA_TYPE_DECIMAL_LENGTH "\nIntroduza o comprimento da parte decimal(Ex:2;5): "
#define MENU_DATA_TYPE_STRING_TYPE1 "#   1.Letras Maiúsculas + espaço                          #\n"
#define MENU_DATA_TYPE_STRING_TYPE2 "#   2.Letras minúsculas + espaço                          #\n"
#define MENU_DATA_TYPE_STRING_TYPE3 "#   3.Letras Maiúsculas + espaço + caracteres especiais   #\n"
#define MENU_DATA_TYPE_STRING_TYPE4 "#   4.Letras minúsculas + espaço + caracteres especiais   #\n"
#define MENU_DATA_TYPE_NUM_TYPE1 "#   5.Números inteiros                                    #\n"
#define MENU_DATA_TYPE_NUM_TYPE2 "#   6.Números decimais                                    #\n"
#define MENU_DATA_TYPE_STRING_TYPE5 "#   7.Letras Maiúsculas + minúsculas + números + espaço   #\n"
#define MENU_DATA_TYPE_STRING_TYPE6 "#   8.Todos os caracteres                                 #\n"

#define MENU_SELECTED_OPTION_1 "Opção 1 selecionada - Letras Maiúsculas + espaço\n"
#define MENU_SELECTED_OPTION_2 "Opção 2 selecionada - Letras minúsculas + espaço\n"
#define MENU_SELECTED_OPTION_3 "Opção 3 selecionada - Letras Maiúsculas + espaço + caracteres especiais\n"
#define MENU_SELECTED_OPTION_4 "Opção 4 selecionada - Letras minúsculas + espaço + caracteres especiais\n"
#define MENU_SELECTED_OPTION_5 "Opção 5 selecionada - Números inteiros\n"
#define MENU_SELECTED_OPTION_6 "Opção 6 selecionada - Números decimais\n"
#define MENU_SELECTED_OPTION_7 "Opção 7 selecionada - Letras Maiúsculas + minúsculas + números + espaço\n"
#define MENU_SELECTED_OPTION_8 "Opção 8 selecionada - Todos os caracteres\n"

#define MENU_RETURN_OPTION "\n\nDeseja voltar ao menu (S - sim; N - não): "
#define MENU_REGEX_GETCHE "Escolha o tipo de validação que deseja (1-Getche; 2-Regex): "

#define MENU_DATA_ENTRY "\nIntroduza os dados que deseja: "
#define MENU_DATA_RESULT "Dados inseridos: "
#define MENU_DATA_RESULT_REGEX "Dados inseridos: %s"
#define MENU_DATA_INVALID "\nValidação de dados incorreta!"
#define MENU_EXIT_PROGRAM "\n\nA sair do programa..."
